import { test,expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { createSession } from '../../src/lib/session';
const secret='integration-session-'+'c'.repeat(40);
async function signIn(page:import('@playwright/test').Page,id='789'){await page.context().addCookies([{name:'__Host-conan-session',value:await createSession({id,name:'Fixture Staff'},secret),url:'https://localhost:3000',secure:true,httpOnly:true,sameSite:'Lax'}]);}

test('session and live staff checks protect the dashboard',async({page})=>{await page.goto('/dashboard');await expect(page).toHaveURL(/login/);await signIn(page,'999');await page.goto('/dashboard');await expect(page).toHaveURL(/login/);});

test('production CSP, real Core data and accessible overview',async({page})=>{const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await signIn(page);const response=await page.goto('/dashboard');await expect(page.getByRole('heading',{name:'Overview',exact:true})).toBeVisible();expect(response?.headers()['content-security-policy']).toContain("'nonce-");expect(response?.headers()['content-security-policy']).not.toContain('unsafe-inline');await expect(page.getByText('MemoryStore',{exact:true})).toBeVisible();expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);expect(errors).toEqual([]);await page.screenshot({path:'test-results/overview.png',fullPage:true});});

test('revision conflict preserves edits and reload is explicit',async({page})=>{await signIn(page);await page.goto('/dashboard/settings');const footer=page.getByLabel('Embed Footer',{exact:true});await footer.fill('Unsaved local edit');const loaded=await (await page.request.get('/api/core/config')).json();const saved=await page.request.put('/api/core/config',{headers:{Origin:'https://localhost:3000'},data:{config:loaded.config,revision:loaded.config.revision}});expect(saved.status()).toBe(200);await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('button',{name:'Reload latest configuration'})).toBeVisible();await expect(footer).toHaveValue('Unsaved local edit');await page.getByRole('button',{name:'Reload latest configuration'}).click();await expect(footer).not.toHaveValue('Unsaved local edit');});

test('command publication requires confirmation and reaches Core',async({page})=>{await signIn(page);await page.goto('/dashboard/commands');await page.getByRole('button',{name:'Publish command changes',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect(page.getByText('Action completed',{exact:true})).toBeVisible();});

test('sandbox is isolated and log records paginate',async({page})=>{await signIn(page);await page.goto('/dashboard/ai/providers');await page.getByLabel('Message',{exact:true}).fill('hello');await page.getByRole('button',{name:'Test reply',exact:true}).click();await expect(page.getByText(/Sandbox fixture reply/)).toBeVisible();await page.goto('/dashboard/logs');const rows=page.locator('ul.records > li');await expect(rows).toHaveCount(50);await page.getByRole('button',{name:'Load more',exact:true}).click();await expect.poll(()=>rows.count()).toBeGreaterThan(50);});

test('mutations reject foreign origins and mobile forms remain accessible',async({page})=>{await signIn(page);const denied=await page.request.post('/api/core/bot/restart',{headers:{Origin:'https://foreign.test'},data:{}});expect(denied.status()).toBe(403);await page.setViewportSize({width:390,height:844});await page.goto('/dashboard/weather');await expect(page.getByRole('heading',{name:'Weather',exact:true})).toBeVisible();expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);});
