"use client";
import { useEffect,useState } from "react";
import { api,ApiError,type ConfigEnvelope } from "@/lib/api";
import { updatePath,type JsonValue } from "@/lib/forms";
import { FormFields } from "./form-fields";
import { Confirmation } from "./confirmation";
export function ConfigEditor({initial,section,keys,defaults}:{initial:ConfigEnvelope;section:string;keys?:string[];defaults:JsonValue}){
  const [saved,setSaved]=useState(initial),[draft,setDraft]=useState(initial.config as unknown as JsonValue),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[reset,setReset]=useState(false),[conflict,setConflict]=useState(false);
  const dirty=JSON.stringify(draft)!==JSON.stringify(saved.config);
  useEffect(()=>{if(!dirty)return;const leave=(e:BeforeUnloadEvent)=>{e.preventDefault();};const navigate=(e:MouseEvent)=>{const anchor=(e.target as HTMLElement).closest("a");if(anchor&&anchor.href!==location.href&&!window.confirm("Leave without saving changes?"))e.preventDefault();};window.addEventListener("beforeunload",leave);document.addEventListener("click",navigate,true);return()=>{window.removeEventListener("beforeunload",leave);document.removeEventListener("click",navigate,true);};},[dirty]);
  const config=draft as {[key:string]:JsonValue},value=config[section];const selected=keys&&value&&typeof value==="object"&&!Array.isArray(value)?Object.fromEntries(Object.entries(value).filter(([key])=>keys.includes(key))):value;
  async function save(){setBusy(true);setMessage("");try{const result=await api<ConfigEnvelope>("config",{method:"PUT",body:JSON.stringify({config:draft,revision:saved.config.revision})});setSaved(result);setDraft(result.config as unknown as JsonValue);setConflict(false);setMessage("Saved");}catch(error){if(error instanceof ApiError&&error.status===409)setConflict(true);setMessage(error instanceof ApiError?error.message+(error.requestId?` · Request ${error.requestId}`:"")+(error.fields.length?" · "+error.fields.map(x=>x.path+": "+x.message).join("; "):""):"Could not save");}finally{setBusy(false);}}
  async function reload(){const result=await api<ConfigEnvelope>("config");setSaved(result);setDraft(result.config as unknown as JsonValue);setConflict(false);setMessage("Latest configuration loaded");}
  function resetSection(){let result=draft;const source=(defaults as {[key:string]:JsonValue})[section];if(keys&&source&&typeof source==="object"&&!Array.isArray(source)){for(const key of keys)if(key in source)result=updatePath(result,[section,key],source[key]);}else result=updatePath(result,[section],source);setDraft(result);setReset(false);}
  return <section className="card"><div className="row spread"><span className="badge">Schema 4 · Revision {saved.config.revision??0}</span><span role="status">{dirty?"Unsaved changes":"Up to date"}</span></div><div className="form-grid"><FormFields value={selected} path={[section]} onChange={(path,value)=>setDraft(updatePath(draft,path,value))}/></div><div className="save-bar"><button className="primary" disabled={!dirty||busy} onClick={save}>{busy?"Saving…":"Save changes"}</button><button onClick={()=>setReset(true)}>Reset section to defaults</button>{conflict&&<button onClick={()=>void reload()}>Reload latest configuration</button>}</div>{message&&<p role={conflict?"alert":"status"}>{message}</p>}{reset&&<Confirmation title="Reset this section?" onConfirm={resetSection} onCancel={()=>setReset(false)}/>}</section>;
}
