"use client";
import fieldRules from "@/lib/field-rules.json";
import { label,type JsonValue } from "@/lib/forms";
export function FormFields({value,path,onChange}:{value:JsonValue;path:string[];onChange:(path:string[],value:JsonValue)=>void}){
  const rule=(fieldRules as Record<string,{enum?:string[];minimum?:number;maximum?:number;minLength?:number;maxLength?:number;arrayObjects?:boolean}>)[path.map(key=>/^\d+$/.test(key)?"*":key).join(".")]||{};
  if(value===null)return null;
  if(Array.isArray(value)){return <fieldset><legend>{label(path.at(-1)||"Items")}</legend>{value.every(x=>typeof x==="string")&&!rule.arrayObjects?<label>One entry per line<textarea rows={Math.min(8,Math.max(2,value.length))} value={value.join("\n")} onChange={e=>onChange(path,e.target.value?e.target.value.split("\n"):[])}/></label>:<>{value.map((item,index)=><div className="list-entry" key={index}><FormFields value={item} path={[...path,String(index)]} onChange={onChange}/><button onClick={()=>onChange(path,value.filter((_,i)=>i!==index))}>Remove entry {index+1}</button></div>)}<button onClick={()=>onChange(path,[...value,path.at(-1)==="triggers"?{id:crypto.randomUUID(),word:"",channelIds:[],mediaUrl:"",responseText:"",enabled:true}:{enabled:true,status:"online",activityType:"listening",activityText:"",streamUrl:""}])}>Add entry</button></>}</fieldset>;}
  if(typeof value==="object")return <>{Object.entries(value).filter(([key])=>!["schemaVersion","revision"].includes(key)).map(([key,item])=>typeof item==="object"?<fieldset key={key}><legend>{label(key)}</legend><FormFields value={item} path={[...path,key]} onChange={onChange}/></fieldset>:<FormFields key={key} value={item} path={[...path,key]} onChange={onChange}/>)}</>;
  const name=label(path.at(-1)||"Value"),id="field-"+path.join("-");
  if(typeof value==="boolean")return <label className="switch" htmlFor={id}><input id={id} type="checkbox" checked={value} onChange={e=>onChange(path,e.target.checked)}/>{name}</label>;
  if(typeof value==="number")return <label htmlFor={id}>{name}<input id={id} type="number" step="any" min={rule.minimum} max={rule.maximum} value={value} onChange={e=>{if(e.target.value!=="")onChange(path,Number(e.target.value));}}/></label>;
  if(rule.enum)return <label htmlFor={id}>{name}<select id={id} value={value} onChange={e=>onChange(path,e.target.value)}>{rule.enum.map(option=><option key={option} value={option}>{label(option)}</option>)}</select></label>;
  return <label htmlFor={id}>{name}{value.length>120||/prompt|instructions|personality|template/i.test(path.at(-1)||"")?<textarea id={id} minLength={rule.minLength} maxLength={rule.maxLength} rows={4} value={value} onChange={e=>onChange(path,e.target.value)}/>:<input id={id} minLength={rule.minLength} maxLength={rule.maxLength} value={value} onChange={e=>onChange(path,e.target.value)}/>}</label>;
}
