"use client";
import { useState } from "react";
import { api } from "@/lib/api";
import { Confirmation } from "./confirmation";
type RecordRow={recordId?:string;name?:string;event?:string;createdAt?:string;mediaType?:string;channelId?:string;previewUrl?:string;messageUrl?:string;webViewLink?:string;payload?:{actorId?:string;requestId?:string}};
type Page={items:RecordRow[];nextCursor:string|null};
function safeUrl(value?:string){try{const url=new URL(value||"");return url.protocol==="https:"&&!url.username&&!url.password?url.href:null;}catch{return null;}}
export function Records({kind,initial,initialCursor=null}:{kind:"media"|"logs";initial:RecordRow[];initialCursor?:string|null}){
  const [rows,setRows]=useState(initial),[search,setSearch]=useState(""),[type,setType]=useState(""),[channel,setChannel]=useState(""),[message,setMessage]=useState(""),[pending,setPending]=useState<RecordRow|null>(null),[cursor,setCursor]=useState(initialCursor),[applied,setApplied]=useState("limit=50"),[busy,setBusy]=useState(false);
  async function refresh(more=false){setBusy(true);const query=new URLSearchParams(more?applied:{limit:"50",search,media_type:type,channel_id:channel});if(more&&cursor)query.set("cursor",cursor);try{const data=await api<Page>(kind+"?"+query);setRows(previous=>more?[...previous,...data.items]:data.items);setCursor(data.nextCursor);if(!more)setApplied(query.toString());setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Request failed");}finally{setBusy(false);}}
  async function remove(){if(!pending?.recordId)return;setBusy(true);try{await api("media/"+pending.recordId,{method:"DELETE"});setRows(previous=>previous.filter(r=>r.recordId!==pending.recordId));setMessage("Media deleted");}catch(error){setMessage(error instanceof Error?error.message:"Delete failed");}finally{setPending(null);setBusy(false);}}
  return <section className="card"><form className="row" onSubmit={e=>{e.preventDefault();void refresh();}}><label>Search {kind}<input type="search" maxLength={100} value={search} onChange={e=>setSearch(e.target.value)}/></label>{kind==="media"&&<><label>Media type<select value={type} onChange={e=>setType(e.target.value)}><option value="">All</option><option value="image">Images</option><option value="video">Videos</option></select></label><label>Channel ID<input inputMode="numeric" pattern="[0-9]*" maxLength={20} value={channel} onChange={e=>setChannel(e.target.value)}/></label></>}<button disabled={busy}>Search</button></form><p role="status">{message}</p><ul className="records">{rows.map((r,i)=>{const preview=safeUrl(r.previewUrl),drive=safeUrl(r.webViewLink),discord=safeUrl(r.messageUrl);return <li key={r.recordId||i}><strong>{r.name||r.event}</strong><time>{r.createdAt}</time>{preview&&r.mediaType==="image"&&<>
    {/* Private expiring URLs must bypass the public Next image optimizer cache. */}
    {/* eslint-disable-next-line @next/next/no-img-element */}
    <img src={preview} alt={r.name||"Archived media"} loading="lazy" referrerPolicy="no-referrer" className="media-preview"/>
  </>}{preview&&r.mediaType==="video"&&<video src={preview} controls preload="none" className="media-preview"/>}{r.payload?.actorId&&<p>Actor {r.payload.actorId}</p>}{r.payload?.requestId&&<button onClick={()=>navigator.clipboard.writeText(r.payload!.requestId!)}>Copy request ID</button>}<div className="row">{drive&&<a href={drive} target="_blank" rel="noreferrer">Open Drive</a>}{discord&&<a href={discord} target="_blank" rel="noreferrer">Discord message</a>}{kind==="media"&&<button disabled={busy} onClick={()=>setPending(r)}>Delete</button>}</div></li>;})}</ul>{!rows.length&&<p>No records yet.</p>}{cursor&&<button disabled={busy} onClick={()=>void refresh(true)}>Load more</button>}{pending&&<Confirmation title="Delete media and its Drive file?" onConfirm={()=>void remove()} onCancel={()=>setPending(null)}/>}</section>;
}
